### ISSUE TITLE
testpage

### ISSUE THREAD

**Issue by Purple906** [Purple906/Marks_Panara#3]
@mysterycommand can you check the code on the test page? I just copied it from a blog and changed a couple things to match closer to what I will need with the panara page. (disregard some of the style within the popup, thats just a place holder for now).

The css has 4 separate pieces all to make the hover work, which it does. I just didn't know if this was best practice or if there is a shorter way to get the same effect? You can see what I did with the original product.html page, and see how the pop up is quite right ... it doesn't pop up in a separate window but on the actual webpage (just hover over the first image in the content_box).

**Comment by mysterycommand** [comment]
Sounds like this is not an issue an more, since we're planning on using the Square embed/store thing.
