### ISSUE TITLE
Next Steps

### ISSUE THREAD

**Issue by mysterycommand** [Purple906/Marks_Panara#5]
- [x] Merge PR #4.
- [x] Pull all the CSS into a unified style sheet (start with the index page).
- [x] Optionally, while you're doing the style unification, you could get rid of all those id selectors (the ones that start with #). Best practice is to use class selectors wherever possible, and I really don't think anything about your pages _requires_ an id at this point.
- [x] Merge my forthcoming "dotfiles" PR so that you don't have trailing whitespace, and we're set up to start doing whatever custom JS we might want to do.
- [x] Put this baby up on [GitHub Pages](https://pages.github.com/).
- [x] Start messing with the embed code stuff … Google Maps might be an easy place to start/practice … it's public and maybe takes less configuration? … or just jump right into the Square embed.

**Comment by Purple906** [comment]
All done except for the GitHub Pages, which I am trying to figure out right meow. I still just get lost in some of the terminology on this website. I know I'm a user, but do I want to create user site or a project site.
